### ISSUE TITLE
Move from regex to extension embedded url searching array

### ISSUE THREAD

**Issue by NeonKatVT** [WebSnke/Nintendo-3DS-Music#10]
Although RegEx is good, it is confusing to read to some coders these days. That's why I recommend switching from RegEx single line to an array with multiple lines of url RegEx in another file as part of the extension code so you don't have to arrange it in the main file every time.

**Benefits**:
- Better readable way of detecting certain domains
- Instead of using strings, able to utilize multiple entries via a file can help find the right match
- Every domain added, there will no longer have the need to update the main code file

**How to achieve**:
1. Create two separate files, one is called "settingsDomains.json" and another called "shoppingDomains.json"
2. Have the extension read that instead for easier matching for each entry instead of just one. Utilize loops and variables for this method to detect if it's settings or a shopping domain.
3. Publish changes after testing phase is over.

**Format of detection .json files**:
Here is a following example websites for shopping in a single file. This same format can be done for settings too.
```json
[
    "store.steampowered.com",
    "*.amazon.com",
]
```

**Comment by psjnek** [comment]
I see your point, and that method would make adding new entries easier. However, regex lets us specify the website name and only triggers in the intended cases. I do not really see any real issue here. This is just a silly browser extension after all and I do not want to break it.

**Comment by psjnek** [comment]
Thank you for your suggestions. I really appreciate them. Never thought that anyone would really take a look at the code.
