### ISSUE TITLE
Add mobile support

### ISSUE THREAD

**Issue by NeonKatVT** [WebSnke/Nintendo-3DS-Music#11]
Firefox on mobile does support extensions, including ones that were meant as an acessory such as this to add enhancement to browsing.

Consider adding mobile support as well for mobile firefox users.

**Comment by psjnek** [comment]
The extension really only has a hand full of users. I do not think that there is that much demand for it on mobile. Thanks for the suggestion anyway.

**Comment by NeonKatVT** [comment]
I did manage to test this on mobile via changing the extension website from mobile to desktop.

**Comment by psjnek** [comment]
> I did manage to test this on mobile via changing the extension website from mobile to desktop.

Sure, but do you really think anyone would use it on mobile?

**Comment by NeonKatVT** [comment]
> > I did manage to test this on mobile via changing the extension website from mobile to desktop.
> 
> Sure, but do you really think anyone would use it on mobile?

I use it right now! It does have issues saving the setting properly on mobile. Unsure why.
