### ISSUE TITLE
Add Firefox Add-ons

### ISSUE THREAD

**Issue by BananaZomber** [WebSnke/Nintendo-3DS-Music#3]
Do I just need to write the name of the website in line 10 or 11 and commit?

By the way, love this extension, great work ^^

**Comment by WebSnke** [comment]
It depends on whether you want to add the settings page of a website or a shopping website.
Which shop or settings page would you like to add?

**Comment by BananaZomber** [comment]
Ohh okey, I think I get it. And the code around the names of the websites is a pattern that saves you from putting the whole URL.
I thought of adding the Firefox add-ons page (https://addons.mozilla.org/es/firefox/)
How would you do it?
(Thanks for the reply btw)

**Comment by BananaZomber** [comment]
Yes, although in this case I wouldn't know how to do it. 
While the other sites followed the structure "site.domain", this one is addons.mozilla.org

**Comment by WebSnke** [comment]
> Yes, although in this case I wouldn't know how to do it. While the other sites followed the structure "site.domain", this one is addons.mozilla.org

Yeah, I would leave the subdomain out.

So, you would add "mozilla" with a "|" between GitHub and Reddit. Then, you would add "edit" with a "|" next to "settings".

**Comment by WebSnke** [comment]
The reason why is because the settings page of addons.mozilla is https://addons.mozilla.org/en-US/firefox/users/edit.

**Comment by BananaZomber** [comment]
Wokey, I think now I get how to add any site.
Thanks for all the help ^^

**Comment by WebSnke** [comment]
Feel free to open as many issues as you need. I will close this one now and you can open a new one once you want to add a new settings page or shop.

**Comment by WebSnke** [comment]
Feel free to open as many issues as you need. I will close this one now and you can open a new one once you want to add a new settings page or shop.

**Comment by WebSnke** [comment]
> Thanks for all the help ^^

You're welcome.
